baseurl = "http://perlcast.net"
languageCode = "en-us"
title = "Perlcast"
theme = "castanet"
googleAnalytics = ""
disqusShortname = ""
paginate = "9"


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

[[Menu.Main]]
    name = "Episodes"
    identifier = "episides"
    url = "/"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "guest"

[params]
favicon = "/favicon.ico"
site_theme = "grey"
# site_layout = "grid"
site_layout = "grid"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
about_logo = "/img/perlcast_logo.png"
copyright_notice = "Copyright 2018 [Participants on the Perlcast](https://www.perlcast.com)"
itunes_subscribe = "http://itunes.apple.com/us/podcast/"
android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/"
google_play_subscribe = "https://goo.gl/app/playmusic?"
stitcher_subscribe = "http://www.stitcher.com/podcast/"
pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "The Perlcast is a show all about the Perl Programming Language and the Perl6 Programming language, along with the people, tools, projects in the Perl community."
media_prefix = ""
  [params.feed]
    copyright = "Copyright 2018 the Perlcast" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "The Perl Programming language podcast" #no markdown or HTML
    itunes_author = "Perlcast" #no markdown or HTML
    itunes_summary = "The Perlcast is a show all about the Perl Programming Language and the Perl6 Programming language, along with the people, tools, projects in the Perl community."
    itunes_owner_name = "Perlcast"
    itunes_owner_email = "hello@perlcast.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.perlcast.com/img/perlcast-logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"
    language = "en-us"

  [params.social]
    github = "PerlPodcast"
    twitter = ""
    twitter_domain = "perlcast.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    googleplus = ""
    pinterest = ""
    instagram = ""
    youtube = ""
    linkedin = ""

  [params.authors]
    [params.authors.Josh]
      name	= "Josh McAdams"
      thumbnail = "img/host/perlcast_logo_head.png"
      bio = "Matt Stratton is a solutions architect at Chef, where he demonstrates how Chef’s automation platform provides speed and flexibility to clients’ infrastructure. He is devoted to concepts like Continuous Delivery and Infrastructure as Code, and his license plate actually says “DevOps”. He lives in Chicago and has an unhealthy obsession with Doctor Who, Firefly, and Game of Thrones. And whiskey."
      [params.authors.Josh.social]
        cpan = ""
        github = "mattstratton"
        facebook = "matt.stratton"
        twitter = "mattstratton"
        linkedin = "mattstratton"
        homepage = "https://www.mattstratton.io"
        pinterest = "mattstratton"
        instagram = "instagram"
        youtube = "mattstratton"
    [params.authors.Mohammad]
			name = "Mohammad Anwar"
      capn = ""
			thumbnail = "img/host/mohammad_anwar.jpg"
			bio = ""
				[params.authors.Mohammad.social]
					twitter = "trevorghess"
    [params.authors.Lance]
      name = "Lance Wicks"
      cpan = ""
      thumbnail = "img/host/lance.jpg"
      bio = ""
      [params.authors.Lance.social]
        twitter = "lancew"
